<ul>
<li>(<em>What</em>) My goal is to improve the quality of responses and decrease the time to taken to solve AskMyHR inquiries <em>(Why)</em> to ensure the best possible outcomes for clients as they conduct their work in the BCPS. (<em>How</em>) I will do this by triaging the requests I receive each day into categories by content, priority, and complexity so that I gain efficiencies when responding<em>.</em> (<em>Measure)</em> I will know I have been successful if I reduce the average response time per request by 10% and increase the average number of client requests I respond to per month by 15%.</li>
</ul>
<ul>
<li><em>(What)</em> My goal is to shift to a coaching leadership style, <em>(Why)</em> so that I can bring out the best in my team. <em>(How)</em> I will do this by completing the Supervising in the BC Public Service (SBCPS) program, signing up for Leadership Coaching, and by having ongoing conversations with my team members about their work. <em>(Measure)</em> Achievement will be measured through ongoing annual improvement in my 360-degree feedback scores.</li>
</ul>
<ul>
<li><em>(What)</em> I will hone my conceptual thinking competency by researching and presenting three ideas for potential future study to my team, <em>(Why)</em> to inform land use practice and stakeholder engagement in the ministry. <em>(How)</em> The ideas will stem from a review of survey data from the past three years, and will consider trends, patterns, gaps, and best practice. <em>(Measure)</em> Achievement will be measured by the degree to which the senior team members determine the ideas are strategically related, have potential for impact, and are feasible.</li>
</ul>
<ul>
<li><em>(What)</em> My goal is to persuade my ministry&rsquo;s executives of the important service the Tree Health Team provides <em>(Why)</em> to ensure my team is adequately funded and supported. <em>(How)</em> I will do this by raising the profile of my team&rsquo;s work at regular reporting intervals so executive are better aware of our work as well as by providing a business case for an additional FTE and increased budget. <em>(Measure)</em> I will know I have been successful if I obtain an additional FTE and an additional 15% to our operating budget by end of the fiscal year.</li>
</ul>
<ul>
<li><em>(What)</em> I will facilitate two in-house consultations in the next 12 months for the employee engagement app development team <em>(Why)</em> to help increase engagement in the BC Public Service. <em>(How)</em> This will be done by helping the team clearly identify their goals and objectives prior to the meeting, developing a facilitation plan, and practicing basic elements of facilitation. <em>(Measure)</em> Achievement will be evaluated by team members though a feedback survey focused on questions regarding trust fostered by the facilitator and degree to which team goals were achieved.</li>
</ul>